/* launches.cpp  --  Upcoming Space Launches pane for HamClock.
 *
 * Data is fetched from the OHB backend (fetch_launches.py) which queries
 * the Launch Library 2 API (The Space Devs) and writes a plain-text cache
 * served at launches_page.
 *
 * File format (generated by fetch_launches.py):
 *   Line 1:   credit string
 *   Per launch (3 lines):
 *     <net_unix_ts> <status_abbrev> <display_name>
 *     <provider_abbrev> @ <location>
 *     <web_page_url>
 *
 * Status colour coding:
 *   Go   → green background + white text
 *   TBC  → yellow text
 *   Hold → orange text
 *   TBD / anything else → grey text
 *
 * Touch behaviour:
 *   Tap a launch row  → popup menu with "Open web page" option
 *   Tap scroll arrows → scroll list up / down
 */

#include "HamClock.h"


// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

// Path on OHB backend (httpHCGET prepends "/ham/HamClock")
static const char launches_page[] = "/launches/launches.txt";
static const char launches_fn[]   = "launches.txt";

#define LAUNCHES_MAXAGE   1800          // refresh from OHB when cache older than this (secs, 30 min)
#define LAUNCHES_MINSIZ   10            // accept even a credit-only file

#define LAUNCHES_INTERVAL (2)           // pane redraw interval, secs (low: we draw a live countdown)

// ---------------------------------------------------------------------------
// Layout
// ---------------------------------------------------------------------------

#define LAUNCH_TITLE_DY   PANETITLE_H   // pane title baseline
#define LAUNCH_CREDITS_DY SUBTITLE_Y0   // source credit line
#define LAUNCH_START_DY   LISTING_Y0    // first entry name baseline
#define LAUNCH_ROW_H      24            // total height of one 2-line entry (px)
#define LAUNCH_NAME_DY    0             // name line: offset from row top (px)
#define LAUNCH_INFO_DY    12            // info line: offset from row top (px)

// ---------------------------------------------------------------------------
// Colours
// ---------------------------------------------------------------------------

#define LAUNCH_TITLE_COLOR  RGB565(100,180,255)  // pane title: light blue (space theme)
#define LAUNCH_GO_BG        RGB565(20,80,20)     // "Go" row background: dark green
#define LAUNCH_GO_COLOR     RGB565(80,230,80)    // "Go" text: bright green
#define LAUNCH_TBC_COLOR    RGB565(255,200,0)    // "TBC" text: yellow
#define LAUNCH_HOLD_COLOR   RGB565(255,140,0)    // "Hold" text: orange
#define LAUNCH_TBD_COLOR    GRAY                 // "TBD" / unknown: grey
#define LAUNCH_INFO_COLOR   BRGRAY              // info line (provider @ loc): light grey
#define LAUNCH_DIV_COLOR    LAUNCH_TITLE_COLOR  // divider line between entries

// ---------------------------------------------------------------------------
// Data structures
// ---------------------------------------------------------------------------

typedef struct {
    time_t   net_t;                     // NET launch time (UTC)
    char    *name;                      // malloced display name
    char    *info;                      // malloced "provider @ location" string
    char    *url;                       // malloced web page URL
    char     status[8];                 // status abbrev: "Go", "TBC", "TBD", "Hold", ...
} LaunchEntry;

static LaunchEntry  *launches;          // malloced array, count = ls_ss.n_data
static char         *launch_credit;     // malloced credit / attribution line
static ScrollState   ls_ss;            // scroll state

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/* Return the display colour for a given status abbreviation. */
static uint16_t statusColor (const char *abbrev)
{
    if (strcmp(abbrev, "Go")   == 0) return LAUNCH_GO_COLOR;
    if (strcmp(abbrev, "TBC")  == 0) return LAUNCH_TBC_COLOR;
    if (strcmp(abbrev, "Hold") == 0) return LAUNCH_HOLD_COLOR;
    return LAUNCH_TBD_COLOR;
}

/* Build a compact countdown / date-time string for NET time t relative to now.
 * Result is written into buf[buf_l].
 */
static void formatLaunchTime (time_t net_t, char *buf, size_t buf_l)
{
    time_t now   = myNow();
    long   delta = (long)(net_t - now);           // seconds until launch

    if (delta < -3600) {
        // Should have been filtered out, but just in case
        snprintf (buf, buf_l, "Past");
    } else if (delta < 0) {
        snprintf (buf, buf_l, "Launching!");
    } else if (delta < 3600) {
        // Under 1 hour: show minutes
        snprintf (buf, buf_l, "T-%ldm", delta / 60);
    } else if (delta < 86400) {
        // Under 24 hours: show Hh Mm
        long h = delta / 3600;
        long m = (delta % 3600) / 60;
        snprintf (buf, buf_l, "T-%ldh%02ldm", h, m);
    } else {
        // More than 1 day away: show "Mon DD HH:MMZ"
        struct tm *tm = gmtime (&net_t);
        snprintf (buf, buf_l, "%s %d %02d:%02dZ",
                  monthShortStr (tm->tm_mon + 1),
                  tm->tm_mday,
                  tm->tm_hour,
                  tm->tm_min);
    }
}

/* Free all malloced launch data and reset the scroll state. */
static void freeLaunches (void)
{
    for (int i = 0; i < ls_ss.n_data; i++) {
        free (launches[i].name);
        free (launches[i].info);
        free (launches[i].url);
    }
    free (launches);
    launches = NULL;
    free (launch_credit);
    launch_credit = NULL;
    ls_ss.n_data = 0;
}

// ---------------------------------------------------------------------------
// Drawing
// ---------------------------------------------------------------------------

/* Draw the launches pane. */
static void drawLaunchesPane (const SBox &box)
{
    if (!launch_credit)
        return;

    prepPlotBox (box);

    // ---- Title ----
    selectFontStyle (LIGHT_FONT, SMALL_FONT);
    tft.setTextColor (LAUNCH_TITLE_COLOR);
    static const char *title = "Launches";
    uint16_t tw = getTextWidth (title);
    tft.setCursor (box.x + (box.w - tw) / 2, box.y + LAUNCH_TITLE_DY);
    tft.print (title);

    // ---- Credit ----
    selectFontStyle (LIGHT_FONT, FAST_FONT);
    tft.setTextColor (LAUNCH_TITLE_COLOR);
    uint16_t cw = getTextWidth (launch_credit);
    tft.setCursor (box.x + (box.w - cw) / 2, box.y + LAUNCH_CREDITS_DY);
    tft.print (launch_credit);

    // ---- Entries ----
    selectFontStyle (LIGHT_FONT, FAST_FONT);
    uint16_t y0 = box.y + LAUNCH_START_DY;

    int min_i, max_i;
    if (ls_ss.getVisDataIndices (min_i, max_i) > 0) {
        for (int i = min_i; i <= max_i; i++) {
            LaunchEntry &le = launches[i];
            int      r    = ls_ss.getDisplayRow (i);
            uint16_t row_y = y0 + r * LAUNCH_ROW_H;

            // Green background highlight for "Go" launches
            if (strcmp (le.status, "Go") == 0)
                tft.fillRect (box.x + 1, row_y - 2, box.w - 2, LAUNCH_ROW_H - 1, LAUNCH_GO_BG);

            // ---- Row 1: countdown + name ----
            char time_str[20];
            formatLaunchTime (le.net_t, time_str, sizeof(time_str));

            // Compose: "[T-Xh] Name"
            char name_line[80];
            snprintf (name_line, sizeof(name_line), "%s %s", time_str, le.name);
            maxStringW (name_line, box.w - 4);

            tft.setTextColor (statusColor (le.status));
            tft.setCursor (box.x + 2, row_y + LAUNCH_NAME_DY);
            tft.print (name_line);

            // ---- Row 2: provider @ location ----
            tft.setTextColor (LAUNCH_INFO_COLOR);
            char info_copy[80];
            quietStrncpy (info_copy, le.info, sizeof(info_copy));
            maxStringW (info_copy, box.w - 4);
            tft.setCursor (box.x + 2, row_y + LAUNCH_INFO_DY);
            tft.print (info_copy);

            // ---- Divider ----
            tft.drawLine (box.x + 1,
                          row_y + LAUNCH_ROW_H - 2,
                          box.x + box.w - 2,
                          row_y + LAUNCH_ROW_H - 2,
                          1,
                          LAUNCH_DIV_COLOR);
        }
    }

    // ---- Scroll controls ----
    ls_ss.drawScrollDownControl (box, LAUNCH_TITLE_COLOR, LAUNCH_TITLE_COLOR);
    ls_ss.drawScrollUpControl   (box, LAUNCH_TITLE_COLOR, LAUNCH_TITLE_COLOR);
}

// ---------------------------------------------------------------------------
// Scrolling
// ---------------------------------------------------------------------------

static void scrollLaunchUp (const SBox &box)
{
    if (ls_ss.okToScrollUp()) {
        ls_ss.scrollUp();
        drawLaunchesPane (box);
    }
}

static void scrollLaunchDown (const SBox &box)
{
    if (ls_ss.okToScrollDown()) {
        ls_ss.scrollDown();
        drawLaunchesPane (box);
    }
}

// ---------------------------------------------------------------------------
// Touch / menu
// ---------------------------------------------------------------------------

/* Show a popup menu for the tapped launch entry.
 * Returns true if a full re-schedule is needed, false if just a redraw.
 */
static bool runLaunchMenu (const SCoord &s, const SBox &box)
{
    // Which entry did the user tap?
    LaunchEntry *lep = NULL;
    if (s.y >= box.y + LAUNCH_START_DY) {
        int display_row = (s.y - box.y - LAUNCH_START_DY) / LAUNCH_ROW_H;
        int data_i;
        if (ls_ss.findDataIndex (display_row, data_i))
            lep = &launches[data_i];
    }

    const int indent = 2;

    // Shorten the name so it fits the menu width
    const uint16_t menu_gap = 20;
    char lname[50];
    quietStrncpy (lname, lep ? lep->name : "", sizeof(lname));
    for (uint16_t t_l = getTextWidth(lname); t_l > box.w - 2*menu_gap; t_l = getTextWidth(lname)) {
        char *r_space = strrchr (lname, ' ');
        if (r_space)
            *r_space = '\0';
        else
            lname[strlen(lname) - 1] = '\0';
    }

    // Menu field visibility
    MenuFieldType lname_mft   = lep ? MENU_LABEL  : MENU_IGNORE;
    MenuFieldType webpage_mft = lep ? MENU_TOGGLE : MENU_IGNORE;
    MenuFieldType credit_mft  = lep ? MENU_IGNORE : MENU_TOGGLE;

    enum { LM_NAME, LM_WEBPAGE, LM_CREDIT };

    MenuItem mitems[] = {
        {lname_mft,   false, 0, indent, lname,            0},
        {webpage_mft, false, 1, indent, "Open web page",  0},
        {credit_mft,  false, 2, indent, "Launch Library 2 site", 0},
    };
    const int n_mi = NARRAY(mitems);

    const uint16_t menu_x     = box.x + menu_gap;
    const uint16_t menu_h     = 60;
    const uint16_t menu_max_y = box.y + box.h - menu_h - 5;
    const uint16_t menu_y     = s.y < menu_max_y ? s.y : menu_max_y;
    SBox menu_b = {menu_x, menu_y, 0, 0};
    SBox ok_b;

    MenuInfo menu = {menu_b, ok_b, UF_CLOCKSOK, M_CANCELOK, 1, n_mi, mitems};
    if (runMenu (menu)) {
        if (lep && mitems[LM_WEBPAGE].set)
            openURL (lep->url);
        else if (!lep && mitems[LM_CREDIT].set)
            openURL ("https://thespacedevs.com/llapi");
    }

    return (false);     // no full-schedule needed, just redraw
}

/* Handle touch on the launches pane.
 * Returns true if this pane consumed the touch, false to change pane.
 */
bool checkLaunchesTouch (const SCoord &s, const SBox &box)
{
    if (s.y < box.y + PANETITLE_H) {

        if (ls_ss.checkScrollUpTouch (s, box)) {
            scrollLaunchUp (box);
            return (true);
        }
        if (ls_ss.checkScrollDownTouch (s, box)) {
            scrollLaunchDown (box);
            return (true);
        }

    } else {

        runLaunchMenu (s, box);
        return (true);
    }

    return (false);
}

// ---------------------------------------------------------------------------
// Data retrieval
// ---------------------------------------------------------------------------

/* Remove launches whose NET is more than 1 hour in the past.
 * Returns true if any were removed (triggers a redraw).
 */
static bool prunePastLaunches (void)
{
    bool any_pruned = false;
    time_t cutoff   = myNow() - 3600;

    for (int i = 0; i < ls_ss.n_data; ) {
        if (launches[i].net_t < cutoff) {
            free (launches[i].name);
            free (launches[i].info);
            free (launches[i].url);
            memmove (&launches[i], &launches[i+1],
                     (--ls_ss.n_data - i) * sizeof(LaunchEntry));
            any_pruned = true;
        } else {
            i++;
        }
    }

    if (any_pruned)
        ls_ss.scrollToNewest();

    return (any_pruned);
}

/* Fetch and parse launches.txt from OHB cache.
 * Returns true if successful.
 */
static bool retrieveLaunches (const SBox &box)
{
    bool ok = false;

    FILE *fp = openCachedFile (launches_fn, launches_page, LAUNCHES_MAXAGE, LAUNCHES_MINSIZ);
    if (!fp) {
        Serial.printf ("LCHS: failed to open %s\n", launches_fn);
        return (false);
    }

    updateClocks (false);

    // Reset existing data
    freeLaunches();

    // Compute max visible entries (2-line entries in the available vertical space)
    int max_vis = (box.h - LAUNCH_START_DY) / LAUNCH_ROW_H;
    if (max_vis < 1)
        max_vis = 1;
    ls_ss.init (max_vis, 0, 0, ScrollState::DIR_TOPDOWN);

    char line1[120], line2[80], line3[200];

    // ---- Credit line ----
    if (!fgets (line1, sizeof(line1), fp)) {
        Serial.printf ("LCHS: %s: no credit line\n", launches_fn);
        goto out;
    }
    chompString (line1);
    launch_credit = strdup (line1);
    ok = true;                          // at minimum we got the credit line

    // ---- Three lines per launch ----
    selectFontStyle (LIGHT_FONT, FAST_FONT);

    while (fgets (line1, sizeof(line1), fp)
        && fgets (line2, sizeof(line2), fp)
        && fgets (line3, sizeof(line3), fp)) {

        chompString (line1);
        chompString (line2);
        chompString (line3);

        // Parse line1: "<net_unix> <status_abbrev> <display_name>"
        char *p = line1;
        char *net_str    = p;
        char *status_str = strchr (p, ' ');
        if (!status_str) {
            Serial.printf ("LCHS: malformed line: %s\n", line1);
            continue;
        }
        *status_str++ = '\0';

        char *name_str = strchr (status_str, ' ');
        if (!name_str) {
            Serial.printf ("LCHS: missing name: %s\n", line1);
            continue;
        }
        *name_str++ = '\0';

        time_t net_t = (time_t) atol (net_str);

        // Skip launches more than 1 hour in the past
        if (net_t < myNow() - 3600) {
            Serial.printf ("LCHS: skipping past launch: %s\n", name_str);
            continue;
        }

        // Truncate name to fit pane width
        maxStringW (name_str, box.w - 6);

        // Grow the launches array
        launches = (LaunchEntry*) realloc (launches, (ls_ss.n_data + 1) * sizeof(LaunchEntry));
        if (!launches)
            fatalError ("No memory for %d launches", ls_ss.n_data + 1);

        LaunchEntry &le = launches[ls_ss.n_data++];
        memset (&le, 0, sizeof(LaunchEntry));

        le.net_t = net_t;
        quietStrncpy (le.status, status_str, sizeof(le.status));
        le.name  = strdup (name_str);   // freed in freeLaunches()
        le.info  = strdup (line2);
        le.url   = strdup (line3);

        Serial.printf ("LCHS: [%d] %s %s -> %s\n",
                       ls_ss.n_data, le.status, le.name, le.url);
    }

out:
    fclose (fp);
    Serial.printf ("LCHS: loaded %d launches from %s\n", ls_ss.n_data, launches_fn);
    return (ok);
}

// ---------------------------------------------------------------------------
// Public update function (called from wifi.cpp)
// ---------------------------------------------------------------------------

/* Retrieve (when stale) and draw the launches pane.
 * 'fresh' is true when the pane was just switched to.
 * Returns true on success, false on error.
 */
bool updateLaunches (const SBox &box, bool fresh)
{
    static int retrieve_hour = -1;
    static int retrieve_min  = -1;

    // Stagger the OHB fetch to a random minute within each half-hour
    if (retrieve_min < 0) {
        retrieve_min = random (30);
        Serial.printf ("LCHS: will fetch at %d and %d mins past the hour\n",
                       retrieve_min, retrieve_min + 30);
    }

    bool ok = true;

    // Fetch when fresh (pane just opened) or at our scheduled minutes
    bool time_to_fetch = (retrieve_hour != hour() &&
                          (minute() == retrieve_min || minute() == retrieve_min + 30));

    if (fresh || time_to_fetch) {
        retrieve_hour = hour();
        ok = retrieveLaunches (box);
        if (ok) {
            ls_ss.scrollToNewest();
            fresh = true;
        }
    }

    if (ok) {
        if (prunePastLaunches() || fresh)
            drawLaunchesPane (box);
    } else {
        plotMessage (box, LAUNCH_TITLE_COLOR, "Launches error");
    }

    return (ok);
}
